### ISSUE TITLE
Performance issues when adding or removing (large) objects

### ISSUE THREAD

**Issue by caplod** [ryangjchandler/spruce#104]
I have a shopping cart app where you can shop playing cards.

If I add a Object (ex. deckToAdd) to decks[] it is really slow.
Even worse if the cards Array is bigger than in the example.
it takes sometimes like 10 seconds.

removing a deck it is also really slow. 

to debug I added the function findDecks. 
when you push to decks[] it is running for every card (in my example like 20 times)

Should it not run only once or so?

When I do the same without Spruce it is running fast and findCards gets called only like 2 times

Could that be related to: 
https://github.com/alpinejs/alpine/pull/276
or
https://github.com/alpinejs/alpine/issues/250

HTML:
````    
<div x-data="">

      <button @click="$store.cart.addToDeck()">Add to Deck</button>
      <button @click="$store.cart.removeFromDeck()">Remove Deck</button>
      <template x-for="deck in $store.cart.findDecks()">
        <div x-text="deck.name"></div>
      </template>
</div>

````

JS:

````
Spruce.store('cart', {
          deckToAdd:     {
              // only for debugging
              id: 7,
              name: "Full Set",
              cards: [
                { card_id: 1, title: 'test', quantity:1},
                { card_id: 2, title: 'test', quantity:1},
                { card_id: 3, title: 'test', quantity:1},
                { card_id: 4, title: 'test', quantity:1},
                { card_id: 5, title: 'test', quantity:1},
                { card_id: 6, title: 'test', quantity:1},
                { card_id: 7, title: 'test', quantity:1},
                { card_id: 8, title: 'test', quantity:1},
                { card_id: 9, title: 'test', quantity:1},
                { card_id: 10, title: 'test', quantity:1},
                { card_id: 11, title: 'test', quantity:1},
                { card_id: 12, title: 'test', quantity:1},
                { card_id: 13, title: 'test', quantity:1},
                { card_id: 14, title: 'test', quantity:1},
                { card_id: 15, title: 'test', quantity:1},
                { card_id: 16, title: 'test', quantity:1},
                { card_id: 17, title: 'test', quantity:1},
                { card_id: 18, title: 'test', quantity:1},
                { card_id: 19, title: 'test', quantity:1},
                { card_id: 20, title: 'test', quantity:1},
              ]
            },
          decks: [],
          addToDeck() {
            this.decks.push( this.deckToAdd )
          },
          removeFromDeck() {
            this.decks.splice(0,1)
          },
          findDecks() {
           // this gets called for every item in cards[]
          // why so often?
            console.log('findDecks ran at: ' + Date.now()) 
            return this.decks
          }
})
````

**Comment by ryangjchandler** [comment]
Thanks for opening this issue @caplod.

I haven't looked into this too deeply yet but I'm guessing it's because Spruce has to recursively go through each item in a Proxy to check if it is an `Array` or `Object` and then recursively wrap those items in a `Proxy`.

For each update made to a Proxy, the relevant Alpine components will be updated. I'm guessing for each `card` that gets wrapped in a Proxy, an update call to the Alpine component is made, hence why the `findDecks` method is called so often.

This is something that I'm hoping to tackle in version 3 of Spruce, since I'll be able to utilise a more efficient Proxy / reactivity core (hopefully) exposed by Alpine, instead of having to roll my own whilst still trying to keep the package as light as possible.

Also, generally speaking, it's good to keep things like carts / shopping bags on the server when possible, otherwise all of the state is exposed to the front-end and can be modified at runtime.

**Comment by rubo77** [comment]
so when will v 3.0.0 be released?
