### ISSUE TITLE
Implement `init` hook and `watch` method

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#12]

**Comment by jacksegal** [comment]
Nice!  Hooks was one of the first things I looked for when checking out your repo.

Sure you've got a firm idea of how to implement this, but thought I'd mention the [Livewire Lifecycle Hooks](https://laravel-livewire.com/docs/lifecycle-hooks), particularly: 

- `updating($name, $value)`
- `updated($name, $value)`
- `updatingFoo($value)`
- `updatedFoo($value)`

Would be cool if people could hook into them globally, but also if you fired off a [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) (like [Alpine $dispatch](https://github.com/alpinejs/alpine#dispatch)), so that people could hook inline too.

Something like:

```
// Globally:
Spruce.on('spruceUpdated', (name, value) => console.log(`sucessfully updated ${name} to ${value}`));

// Or inline:
<div x-data>
    <span x-on:spruceUpdated="console.log(`sucessfully updated ${$event.detail.name} to ${$event.detail.value}`)"></span>
</div>
```

Just a suggestion though!  Give me a shout if you're looking for a spare pare of hands...

**Comment by HugoDF** [comment]
`spruceUpdated` is going to cause issues being bound to since HTML isn't case sensitive

Something like `spruce: updated` might work better.

Also not sure about the overhead of triggering a new event for every single change.

Might make more sense to use an explicitly defined watcher syntax (similar to Alpine's `$watch`)

**Comment by jacksegal** [comment]
Yeah, the `spruce:updated` seems to be general convention in other projects too.  (I avoided it for the example because I wasn't sure how Alpine would react to having a colon in event name `x-on:spruce:updated`)

Good point about overhead as well - my main objective was more about being able to hook into the lifecycle inline, rather than the exact implementation.  So as long as the "defined watcher syntax" allowed you to access the before / after, as well as single variable / all variables, then that works.

Just my 2 pence anyway 🤷‍♂️Sure @ryangjchandler has his own ideas...

**Comment by ryangjchandler** [comment]
Hey guys, thanks for the input. My initial thoughts on this were to have a similar syntax to Livewire, where you simply hook into the core using `Spruce.on` as @jacksegal suggested.

They would take the form of a single identifier in most case. The problem with targeting a specific property is that nested properties react too, so syntactically it wouldn't be very nice. I'd probably limit it to "watching" top level properties the same as Alpine does.

@jacksegal Have you got any example use cases where you'd want to use these sort of `updated` or `updating` events, since I imagine most people will actually be using the data so their components will react accordingly.

**Comment by jacksegal** [comment]
Sure - here's a use case for having a "pre update" Event hook - it's one that I used the Livewire `updating` for:

You are building a Profile page where users can update their details - after a user updates a field, you want to show a notification of the change:

![image](https://user-images.githubusercontent.com/9342782/80793455-11984f00-8b8f-11ea-926e-3d0e1bef50f8.png)

If you could access a "pre update" hook, you would have the existing value (in Spruce) as well as the new value that is about to be set ($value).

But I guess you achieve the same thing if you just passed the old value to a "post update" Event hook.

I'm generally a big fan of full lifecycle hooks though (before / after), as I think it provides developers with a lot more flexibility.

**Comment by ryangjchandler** [comment]
Interesting, seems like a fair use case. I've been using Spruce for forms too, I assume you're using it to build light a notifications / alert bus?

**Comment by jacksegal** [comment]
Yes, exactly.

**Comment by ryangjchandler** [comment]
I'm gonna work on these hooks later on today, I'll ping you on the PR and mention this issue to see if you think there's anything missing.
