### ISSUE TITLE
Cannot access store array

### ISSUE THREAD

**Issue by jonasfeige** [ryangjchandler/spruce#132]
Hi there.

Spruce is amazingly helpful, thank you! However, I just ran into a small problem and cannot figure out what is causing it:
I am unable to access `$store` props with the type of `array`. No problems using strings or booleans. Not sure if I am doing something wrong or this is unintended? Here is a simple CodePen that logs items to the console. The saved string works fine, the empty array returns a `Proxy {}`.

Debug view:
[https://cdpn.io/jonasfeige/debug/JjbRPvY/vPMKKgePOGLM](https://cdpn.io/jonasfeige/debug/JjbRPvY/vPMKKgePOGLM)

Regular view:
[https://codepen.io/jonasfeige/pen/JjbRPvY](https://codepen.io/jonasfeige/pen/JjbRPvY)

**Comment by ryangjchandler** [comment]
@jonasfeige Spruce wraps any `Array` or `Object` types in `Proxy` instances so that it can monitor any changes being made. This functionality is actually correct and not a bug. Without it, Spruce wouldn't work correctly.

If you _need_ it to log out the `Array` correctly, you could always use: `console.log([...this.arr])`.
