### ISSUE TITLE
Accessing dynamic store keys

### ISSUE THREAD

**Issue by kilianso** [ryangjchandler/spruce#144]
Hello! Great repo.

I have a scenario where I fetch data from an API and try to create a unique store object for each entry of the array in the response. Here's an example (using Pug)

```    
template(x-for='entry in data')
    li.list__entry(x-init='saveToStore("plan", entry.id, data.plan)')
script.
    function saveToStore(sheet, rowID, data) {
        Spruce.store(`${sheet}-${rowID}`, data);
    }      
```

Now the problem is, how do I access this dynamically created store key using the entry.id of the x-for loop?
I tried something like this, but it's not working:

```
template(x-if=`$store.plan-${entry.id}`)
    span(x-text=`$store.plan-${entry.id}.name`)
```

How to solve this? Or any tip for another workaround?

**Comment by rehhouari** [comment]
`$store['plan-'+entry.id]` and ` $store['plan-'+entry.id].name` should work.
$store is an object, and object elements can be accessed with .dot syntax as well as brackets[].

so your code would be:
```pug
template(x-if=`$store['plan-'+entry.id]`)
    span(x-text=`$store['plan-'+entry.id].name`)
```

Also, consider using Github's new feature, discussions, for such questions since this isn't an issue with Spruce itself ^^

**Comment by ryangjchandler** [comment]
@rehhouari Thanks for responding to this one. That's correct, `$store` is an object so you'll need to use the `[]` syntax when accessing dynamic keys.
