### ISSUE TITLE
`$store is not defined` error?

### ISSUE THREAD

**Issue by yaquawa** [ryangjchandler/spruce#41]
I got an error:

```
Uncaught ReferenceError: $store is not defined
```

Here is my markup:
```html
<script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@0.x.x/dist/spruce.umd.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine-ie11.min.js" defer></script>
```

If I remove the `type="module"` attribute it works. Why? Can't I use it with `type="module"`?

**Comment by ryangjchandler** [comment]
Hey @yaquawa - `type="module"` will affect when the script is loaded - I'm aiming to tackle this in the next release of Spruce so that it works nicely with the module/nomodule pattern.

**Comment by HugoDF** [comment]
Would adding `type="module"` to the Spruce script tag work around the issue?

**Comment by yaquawa** [comment]
@ryangjchandler Do you mean scripts with `type="module"` set become to async load?

**Comment by yaquawa** [comment]
> Would adding `type="module"` to the Spruce script tag work around the issue?

No, same error.

**Comment by ryangjchandler** [comment]
@HugoDF makes a good point - try adding the `type="module"` to the Spruce script tag. I haven't actually tried this since I don't normally use the module/nomodule pattern because supporting legacy browsers sucks. 

It is worth noting that Spruce isn't IE11 compatible either, since there are some polyfills needed for `Proxy` etc.

**Comment by yaquawa** [comment]
@ryangjchandler I didn't get what's the problem with `type="module"` ?

**Comment by ryangjchandler** [comment]
> @ryangjchandler I didn't get what's the problem with `type="module"` ? Why it not works?😓

`type="module"` has the same effect as the `defer` attribute, meaning they are loaded / fetched in parallel to HTML execution, but that causes problems with Spruce since it needs to run *before* Alpine does.

**Comment by yaquawa** [comment]
@ryangjchandler make spruce's script tag with`defer` didn't help. Hope this can be fixed in the next version👍🏼

**Comment by ryangjchandler** [comment]
@yaquawa Well, technically speaking it's not a problem that I can solve since Spruce works on DOM manipulations meaning it has to be done before Alpine loads and runs. Instead, I have to change how Spruce works so that it doesn't rely on DOM manipulations which is possible, but will involve breaking changes and will only support newer versions of Alpine.

**Comment by yaquawa** [comment]
@ryangjchandler That sounds like it's a better solution.
Looking forward to the next version !

**Comment by gavinhewitt** [comment]
Having the same issue. Removing `type="module` is the only thing that works.

**Comment by ryangjchandler** [comment]
Closed this issue - I've decided to keep Spruce's internals fairly similar to how they already were, so you will still need to include Spruce before Alpine or move both to the end of the `<body>` tag.
