### ISSUE TITLE
Persistence is a bit awkward and 'hard' to understand

### ISSUE THREAD

**Issue by Swahjak** [ryangjchandler/spruce#90]
First of all great work!

I find the persistence a bit awkward / hard to understand because of the logic used. That starts with the fact that there is no difference between retrieval and persistence on the API (aside from calling `retrieveFromLocalStorage` directly). Based on other libraries I would expect the `getter` and `setter` to be different functions. The `store` function name feels a bit awkward because the whole thing (Spruce) _is_ a store. If I would bind `Spruce`  to a variable I would call it `store` resulting in a `store.store()` call. 

In general the API would make more sense to me if it would contain a `store.get()` and `store.set()` (and maybe even a `store.persist()` to differentiate between _storing_ and _persisting_.

**Comment by ryangjchandler** [comment]
@Swahjak Thanks for your feedback.

The goal with Spruce is to keep the API as small as possible. I personally find the API for it simple and straightforward, but this is the first report I've had of anybody thinking otherwise, hence why nothing has been changed.

I also wouldn't be able to make any big or breaking API changes before a v3.0 release, which I'm probably going to target for Alpine v3.0.

Assigning `Spruce` to a variable doesn't make much sense to me. Spruce isn't the store, it's the interface that you use to create new stores and it also holds all of the stores on a property.

Instead, what I'd recommend is that you create a store and assign it back to a variable instead.

```js
const userStore = Spruce.store('user', {
    name: 'Ryan'
})
```

Alternatively, if you want to get a store _after_ you've created it, you can use that same method:

```js
const userStore = Spruce.store('user')
```

In that example the `userStore` variable will now hold the `Proxy` that Spruce creates.

> That starts with the fact that there is no difference between retrieval and persistence on the API (aside from calling retrieveFromLocalStorage directly).

There is a difference though, right? When you create a new store and you want it to be persisted, `retrieveFromLocalStorage` is called to see if that store already exists within the "persistence driver".

When an update is made to a store, the `updateLocalStorage` method is called. (This method should be renamed to something like `updatePersistedStore`). See this line: https://github.com/ryangjchandler/spruce/blob/18598e1b99e2d6532709ba631a187a770d60ae6d/src/index.js#L131

**Comment by ryangjchandler** [comment]
I'm going to move this issue into a discussion since it's not directly related to any bugs, etc.
